# Images
jpg     xdg-open
jpeg    xdg-open
png     xdg-open
gif     xdg-open
bmp     xdg-open
webp    xdg-open
svg     xdg-open
tiff    xdg-open
ico     xdg-open

# Video
mkv     xdg-open
avi     xdg-open
mp4     xdg-open
mov     xdg-open
wmv     xdg-open
flv     xdg-open
webm    xdg-open

# Audio
mp3     xdg-open
wav     xdg-open
flac    xdg-open
ogg     xdg-open
aac     xdg-open
m4a     xdg-open

# Documents
pdf     xdg-open
txt     xdg-open
md      xdg-open

# Microsoft Office
doc     xdg-open
docx    xdg-open
xls     xdg-open
xlsx    xdg-open
ppt     xdg-open
pptx    xdg-open
mdb     xdg-open
accdb   xdg-open

# LibreOffice
odt     xdg-open
ods     xdg-open
odp     xdg-open
odg     xdg-open
odf     xdg-open
odb     xdg-open
odm     xdg-open
ott     xdg-open
ots     xdg-open
otp     xdg-open

# Windows executables
exe     wine
msi     wine
