# HackFM configuration file
# 
# open_execute_in_terminal=0
#   0 = run executable in the Ctrl-O terminal (inline, primary screen)
#   1 = open a new terminal window in the current directory and run it there
open_execute_in_terminal=0

# default_editor=
#   Empty = use internal editor
#   Program name = open files with that editor (e.g. vi, nano, mcedit)
#   If the program is not found, an error message will be shown
default_editor=

# Modules
# Enable/disable modules by setting module_NAME_enabled=1 or 0
module_fscopy_enabled=1
module_fsextract_enabled=1
module_quickdir_enabled=1
module_fsattr_enabled=1
module_fsmkdir_enabled=1
module_fsdelete_enabled=1
module_fsmove_enabled=1
module_usermenu_enabled=1
module_viewer_enabled=1
module_editor_enabled=1
module_vimhook_enabled=1
module_colors_enabled=1
